version: 2.1
jobs:
  compile:
   docker:
      - image: ghcr.io/neutron-toolchains/docker-image:arch-neutron
   steps:
      - run:
          no_output_timeout: 50m
          command: |
           git clone https://github.com/rinnsakaguchi/jablay -b personal kernel
           cd kernel
           git clone https://github.com/rinnsakaguchi/myscripts -b master
           chmod +x myscripts/clang-setup.sh
           chmod +x myscripts/surya.sh
           source ./myscripts/clang-setup.sh
           ./myscripts/surya.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile