name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Surya Kernel
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v3

      - name: Prepare timezone 
        run: |
          echo "BUILD_TIME=$(TZ=Asia/Jakarta date '+%d%m%Y-%H%M')" >> $GITHUB_ENV
          sudo rm /etc/localtime
          sudo ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime

      - name: Set Up Dependencies
        run: |
          sudo apt update -y
          sudo apt install bc cpio flex bison aptitude git python-is-python3 tar perl wget curl lz4 -y
          sudo aptitude install libssl-dev -y
          sudo apt install device-tree-compiler -y

      - name: Run SukiSU Kernel Setup
        run: |
          curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-dev

      - name: Clone ZyC Clang
        run: |
          mkdir zyc-clang
          curl -LO https://github.com/ZyCromerZ/Clang/releases/download/20.0.0git-20250129-release/Clang-20.0.0git-20250129.tar.gz
          tar -C zyc-clang/ -xf Clang-20.0.0git-20250129.tar.gz

      - name: Set Environment Variables
        run: |
          echo "KERNEL_DEFCONFIG=surya_defconfig" >> $GITHUB_ENV
          echo "TOOLCHAIN=$(pwd)/zyc-clang" >> $GITHUB_ENV
          echo "PATH=$(pwd)/zyc-clang/bin:$PATH" >> $GITHUB_ENV
          echo "BUILD_USER=mahirooo" >> $GITHUB_ENV
          echo "BUILD_HOST=android-build" >> $GITHUB_ENV
          echo "BUILD_TIME=$(date +%Y%m%d-%H%M)" >> $GITHUB_ENV

      - name: Send Telegram Notification - Build Started
        run: |
          CLANG_VER=$(./zyc-clang/bin/clang --version | head -n 1)
          curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage \
            -d chat_id=${TELEGRAM_CHAT_ID} \
            -d text="🚀 *Build Dimulai!* | *Clang*: ${CLANG_VER} \
            -d parse_mode=Markdown
      
      - name: Set Build Start Time
        run: echo "BUILD_START=$(date +%s)" >> $GITHUB_ENV

      - name: Make Defconfig
        run: |
          make O=out ARCH=arm64 ${KERNEL_DEFCONFIG}

      - name: Build Kernel
        run: |
          make -j$(nproc) O=out \
            ARCH=arm64 \
            LD=ld.lld \
            AS=llvm-as \
            AR=llvm-ar \
            NM=llvm-nm \
            OBJCOPY=llvm-objcopy \
            OBJDUMP=llvm-objdump \
            STRIP=llvm-strip \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_COMPAT=arm-linux-gnueabi- \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            LLVM=1 \
            LLVM_IAS=1 \
            DTC_EXT=dtc \
            KBUILD_COMPILER_STRING="${PWD}/clang" \
            KBUILD_BUILD_USER=${BUILD_USER} \
            KBUILD_BUILD_HOST=${BUILD_HOST} 2>&1 | tee log.txt
        continue-on-error: true

      - name: Send Telegram Notification - Build Failed (if failed)
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument \
            -F chat_id=${TELEGRAM_CHAT_ID} \
            -F document=@log.txt \
            -F caption="❌ Build kernel *gagal*! Berikut log-nya 🧾." \
            -F parse_mode=Markdown

      - name: Check Kernel Output Files
        run: |
          [[ -f out/arch/arm64/boot/Image.gz ]] || { echo "❌ Missing Image.gz"; exit 1; }
          [[ -f out/arch/arm64/boot/dtbo.img ]]  || { echo "❌ Missing dtbo.img"; exit 1; }
          [[ -f out/arch/arm64/boot/dtb.img ]]   || { echo "❌ Missing dtb.img"; exit 1; }

      - name: Fetch AnyKernel3 and Package
        run: |
          git clone --depth=1 https://github.com/rinnsakaguchi/AnyKernel3.git -b FSociety AnyKernel3
          cp out/arch/arm64/boot/Image.gz AnyKernel3/Image.gz
          cp out/arch/arm64/boot/dtbo.img AnyKernel3/dtbo.img
          cp out/arch/arm64/boot/dtb.img AnyKernel3/dtb.img
          cd AnyKernel3
          zip -r9 ../Surya-Kernel-${{ env.BUILD_TIME }}.zip ./*

      - name: Calculate Build Duration
        run: |
          BUILD_END=$(date +%s)
          DURATION=$((BUILD_END - BUILD_START))
          MIN=$((DURATION / 60))
          SEC=$((DURATION % 60))
          echo "BUILD_DURATION=${MIN}m ${SEC}s" >> $GITHUB_ENV

      - name: Generate Changelog
        run: |
          {
            echo "CHANGELOG<<EOF"
            echo "⏱️ Duration: ${{ env.BUILD_DURATION }}"
            git log -n 10 --pretty=format:"• %s (%an)"
            echo "EOF"
          } > changelog.txt
          cat changelog.txt >> $GITHUB_ENV

      - name: Upload Kernel ZIP to GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Surya-Kernel-${{ env.BUILD_TIME }}-mahirooo
          path: Surya-Kernel-${{ env.BUILD_TIME }}.zip

      - name: Send Build to Telegram
        run: |
          curl -F document=@Surya-Kernel-${{ env.BUILD_TIME }}.zip \
          -F caption="${{ env.CHANGELOG }}" \
          -F parse_mode=Markdown \
          "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}"
